name: Copy Staging to Production
on:
  workflow_dispatch:
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Upload to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          remote_host: ${{ secrets.PRODUCTION_HOST }}
          remote_user: ${{ secrets.PRODUCTION_USER }}
          remote_key: ${{ secrets.PRODUCTION_KEY }}
          remote_path: ${{ secrets.PRODUCTION_PATH }}
          switches: -avzr --omit-dir-times --no-owner --no-group --no-perms --delete
          path: ./
